name: testes

on:
  push:
    branches: ["main"]
  
  workflow_dispatch:


jobs:
  test:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:latest
        env:
          MYSQL_ROOT_PASSWORD: 
          MYSQL_DATABASE: workflow
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:

      - uses: actions/checkout@v1
      - run: mysql -h 127.0.0.1 --port 8888 -u root -ppassword -e 'CREATE DATABASE IF NOT EXISTS workflow;'
      
      - name: Checkout from repository
        uses: actions/checkout@v3

      - name: Set up NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: "16.14.0"

      - name: Install package deps
        run: npm install

      - name: Configure the Prisma environment
        run: npx prisma generate
      
      - name: Run tests
        run: npm test