name: testes

on:
  push:
    branches: ["main"]
  
  workflow_dispatch:


jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout from repository
        uses: actions/checkout@v3

      - name: Set up NodeJS
        uses: actions/setup-node@v2
        with:
          node-version: "16.14.0"

      - name: Install package deps
        run: npm install

      - name: Configure the Prisma environment
        run: npx prisma generate
      
      - name: Run tests
        run: npm test